// #region ============================== Imports

// components
import IntroSection from "./_components/IntroSection/IntroSection";
import ContentSection from "./_components/ContentSection/ContentSection";
import Nav from "./_components/Nav/Nav";

// constants
import {
	SANITY_PROJECT_QUERY,
	SANITY_PROJECT_TAGS,
	SANITY_UI_QUERY,
	SANITY_UI_TAGS,
} from "@/constants/sanity";

// sanity
import { sanityFetchData } from "@/app/[lang]/_services/sanityFetchData";

// styles
import css from "./page.module.css";

// types
import type { Metadata } from "next";
import { NavLabel } from "./page.types";

// #endregion ===========================

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface Props {
	params: Promise<{ slug: string; lang: string }>;
}
export default async function HomePage({ params }: Props) {
	// const { slug, lang } = await params;

	// #region ============================== Fetch & process data

	//
	// fetch project UI elements
	const ui = await sanityFetchData({
		query: SANITY_PROJECT_QUERY,
		params: await params,
		tags: SANITY_PROJECT_TAGS,
	});

	//
	// fetch global UI elements
	const uiGlobal = await sanityFetchData({
		query: SANITY_UI_QUERY,
		params: await params,
		tags: SANITY_UI_TAGS,
	});

	//
	// project intro
	const UI_INTRO = {
		title: ui?.title ?? "",
		description: ui?.about?.description ?? "",
		link: {
			label: ui?.about?.buttonTitle ?? "",
			href: ui?.about?.link ?? "",
		},
		details: ui?.details ?? [],
		video: {
			video: ui?.heroVideo?.video ?? {},
			poster: ui?.heroVideo?.poster ?? {},
		},
	};
	const UI_INTRO_STRING = JSON.stringify(UI_INTRO);

	//
	// project challenges & solutions
	const UI_CONTENT = {
		title: uiGlobal?.projectPage?.contentTitle ?? "",
		label: uiGlobal?.projectPage?.challengeTitle ?? "",
		content: ui?.section ?? [],
	};
	const UI_CONTENT_STRING = JSON.stringify(UI_CONTENT);

	//
	// page end
	const UI_END = {
		title: uiGlobal?.projectPage?.endText ?? "",
	};
	const UI_END_STRING = JSON.stringify(UI_END);

	//
	// floating nav
	const navLabels = ui?.section?.map((item: NavLabel) => {
		return {
			label: item?.content[0]?.children[0]?.text ?? "",
			key: item?.content[0]?.children[0]?._key ?? "",
		};
	});
	const UI_NAV = {
		title: uiGlobal?.projectPage?.navTitle ?? "",
		labels: navLabels ?? [],
	};
	const UI_NAV_STRING = JSON.stringify(UI_NAV);

	// #endregion ===========================

	return (
		<main className={css.container}>
			<Nav uiString={UI_NAV_STRING} />
			<IntroSection uiString={UI_INTRO_STRING} />
			<ContentSection
				uiContentString={UI_CONTENT_STRING}
				uiEndString={UI_END_STRING}
			/>
		</main>
	);
}
