import type { Metadata } from "next";
import { Source_Serif_4, IBM_Plex_Mono, Manrope } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/reset.css";
import "@/styles/tokens.colors.css";
import "@/styles/tokens.fonts.css";
import "@/styles/tokens.spacing.css";
import { LayoutTransition } from "@/components/LayoutTransition/LayoutTransition";

const sourceSerif4 = Source_Serif_4({
	variable: "--font-serif",
	subsets: ["latin", "cyrillic"],
	weight: "400",
	style: ["normal", "italic"],
	display: "swap",
});

const imbPlexMono = IBM_Plex_Mono({
	variable: "--font-mono",
	subsets: ["latin", "cyrillic"],
	weight: "500",
	display: "swap",
});

const manrope = Manrope({
	variable: "--font-display",
	subsets: ["latin", "cyrillic"],
	weight: ["500", "600"],
	display: "swap",
});


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ lang: string }>;
}>) {
	const { lang } = await params;

	return (
		<html lang={lang} className={`${sourceSerif4.variable} ${imbPlexMono.variable} ${manrope.variable}`}>
			<body>
				<LayoutTransition
					initial={{ opacity: 0 }}
					animate={{ opacity: 1 }}
					exit={{ opacity: 0 }}
				>
					{children}
				</LayoutTransition>
			</body>
		</html>
	);
}
