// #region ============================== Imports

// components
import HeroSection from "@/app/[lang]/_components/HeroSection/HeroSection";
import AboutSection from "@/app/[lang]/_components/AboutSection/AboutSection";
import ExperienceSection from "@/app/[lang]/_components/ExperienceSection/ExperienceSection";
import AchievementsSection from "@/app/[lang]/_components/AchievementsSection/AchievementsSection";
import ClientsSection from "@/app/[lang]/_components/ClientsSection/ClientsSection";
import ResumeSection from "@/app/[lang]/_components/ResumeSection/ResumeSection";
import ProjectsSection from "@/app/[lang]/_components/ProjectsSection/ProjectsSection";
import ExperimentsSection from "@/app/[lang]/_components/ExperimentsSection/ExperimentsSection";
import ContactSection from "@/components/ContactSection/ContactSection";
import Footer from "@/components/Footer/Footer";
import MenuHome from "@/components/Menu/MenuHome/MenuHome";

// constants
import {
	SANITY_HOME_EXPERIMENTS_QUERY,
	SANITY_HOME_EXPERIMENTS_TAGS,
	SANITY_HOME_PROJECTS_QUERY,
	SANITY_HOME_PROJECTS_TAGS,
	SANITY_HOME_QUERY,
	SANITY_HOME_TAGS,
	SANITY_UI_QUERY,
	SANITY_UI_TAGS,
} from "@/constants/sanity";
import { HOME_SECTIONS } from "@/constants/sectionNames";

// sanity
import { sanityFetchData } from "@/app/[lang]/_services/sanityFetchData";

// styles
import css from "./page.module.css";

// types
import type { Metadata } from "next";

// utility

// #endregion ===========================

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface Props {
	params: Promise<{ lang: string }>;
}
export default async function HomePage({ params }: Props) {
	const { lang } = await params;

	// fetch global UI elements
	const uiGlobal = await sanityFetchData({
		query: SANITY_UI_QUERY,
		params: { lang },
		tags: SANITY_UI_TAGS,
	});
	const uiStringContact = JSON.stringify(uiGlobal?.contact);

	// fetch home UI elements
	const ui = await sanityFetchData({
		query: SANITY_HOME_QUERY,
		params: { lang },
		tags: SANITY_HOME_TAGS,
	});

	const uiStringHero = JSON.stringify(ui?.hero);
	const uiStringAbout = JSON.stringify(ui?.about);
	const uiStringExperience = JSON.stringify(ui?.experience);
	const uiStringAchievements = JSON.stringify(ui?.achievements);
	const uiStringClients = JSON.stringify(ui?.clients);
	const uiStringResume = JSON.stringify([ui?.resume, ui?.file, ui?.fileName]);
	const uiStringProjects = JSON.stringify([ui?.projects, ui?.buttonTitle]);
	const uiStringExperiments = JSON.stringify(ui?.experiments);

	// fetch Projects (preview)
	const projects = await sanityFetchData({
		query: SANITY_HOME_PROJECTS_QUERY,
		params: { lang },
		tags: SANITY_HOME_PROJECTS_TAGS,
	});
	const homeProjectsString = JSON.stringify(projects);

	// fetch Experiments
	const experiments = await sanityFetchData({
		query: SANITY_HOME_EXPERIMENTS_QUERY,
		params: { lang },
		tags: SANITY_HOME_EXPERIMENTS_TAGS,
	});
	const homeExperimentsString = JSON.stringify(experiments?.data);

	return (
		<main>
			<MenuHome
				lang={lang}
				menu={uiGlobal?.menu}
				menuMobile={uiGlobal?.menuMobile}
			/>

			<HeroSection uiString={uiStringHero} />

			<div className={css.container}>
				<div id={HOME_SECTIONS.bio}>
					<AboutSection uiString={uiStringAbout} />
					<ExperienceSection uiString={uiStringExperience} />
					<AchievementsSection uiString={uiStringAchievements} />

					<div className={css.double}>
						<ClientsSection uiString={uiStringClients} />
						<ResumeSection uiString={uiStringResume} />
					</div>
				</div>

				<ProjectsSection
					uiString={uiStringProjects}
					projectsString={homeProjectsString}
				/>
				<ExperimentsSection
					uiString={uiStringExperiments}
					experimentsString={homeExperimentsString}
				/>
			</div>

			<div className={css.container_footer}>
				<ContactSection uiString={uiStringContact} />
				<Footer obj={uiGlobal?.footer} lang={lang} />
			</div>
		</main>
	);
}
