// #region ============================== Imports

// components
import HeroSection from "@/app/[lang]/_components/HeroSection/HeroSection";
import AboutSection from "@/app/[lang]/_components/AboutSection/AboutSection";
import ExperienceSection from "@/app/[lang]/_components/ExperienceSection/ExperienceSection";
import AchievementsSection from "@/app/[lang]/_components/AchievementsSection/AchievementsSection";
import ClientsSection from "@/app/[lang]/_components/ClientsSection/ClientsSection";
import ResumeSection from "@/app/[lang]/_components/ResumeSection/ResumeSection";
import ProjectsSection from "@/app/[lang]/_components/ProjectsSection/ProjectsSection";
import ExperimentsSection from "@/app/[lang]/_components/ExperimentsSection/ExperimentsSection";

// constants
import {
	SANITY_HOME_EXPERIMENTS_QUERY,
	SANITY_HOME_EXPERIMENTS_TAGS,
	SANITY_HOME_PROJECTS_QUERY,
	SANITY_HOME_PROJECTS_TAGS,
	SANITY_HOME_QUERY,
	SANITY_HOME_TAGS,
} from "@/constants/sanity";

// sanity
import { sanityFetchData } from "@/app/[lang]/_services/sanityFetchData";

// styles
import css from "./page.module.css";

// types
import type { Metadata } from "next";

// #endregion ===========================

// TODO
//
// Generate Metadata
// title = hero title
// description = hero subtitle
//
// 1. next js docs - (Memoizing data requests) - https://nextjs.org/docs/app/getting-started/metadata-and-og-images
// 2. base url - https://www.w3.org/TR/2011/WD-html5-author-20110809/the-base-element.html
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface Props {
	params: Promise<{ lang: string }>;
}
export default async function HomePage({ params }: Props) {
	const { lang } = await params;

	// fetch UI elements
	const ui = await sanityFetchData({
		query: SANITY_HOME_QUERY,
		params: { lang },
		tags: SANITY_HOME_TAGS,
	});

	const uiStringHero = JSON.stringify(ui?.hero);
	const uiStringAbout = JSON.stringify(ui?.about);
	const uiStringExperience = JSON.stringify(ui?.experience);
	const uiStringAchievements = JSON.stringify(ui?.achievements);
	const uiStringClients = JSON.stringify(ui?.clients);
	const uiStringResume = JSON.stringify([ui?.resume, ui?.file, ui?.fileName]);
	const uiStringProjects = JSON.stringify([ui?.projects, ui?.buttonTitle]);
	const uiStringExperiments = JSON.stringify(ui?.experiments);

	// fetch Projects (preview)
	const projects = await sanityFetchData({
		query: SANITY_HOME_PROJECTS_QUERY,
		params: { lang },
		tags: SANITY_HOME_PROJECTS_TAGS,
	});
	const homeProjectsString = JSON.stringify(projects);

	// fetch Experiments
	const experiments = await sanityFetchData({
		query: SANITY_HOME_EXPERIMENTS_QUERY,
		params: { lang },
		tags: SANITY_HOME_EXPERIMENTS_TAGS,
	});
	const homeExperimentsString = JSON.stringify(experiments?.data);

	return (
		<main>
			<HeroSection uiString={uiStringHero} />

			<div className={css.container}>
				<AboutSection uiString={uiStringAbout} />
				<ExperienceSection uiString={uiStringExperience} />
				<AchievementsSection uiString={uiStringAchievements} />

				<div className={css.double}>
					<ClientsSection uiString={uiStringClients} />
					<ResumeSection uiString={uiStringResume} />
				</div>

				<ProjectsSection
					uiString={uiStringProjects}
					projectsString={homeProjectsString}
				/>
				<ExperimentsSection
					uiString={uiStringExperiments}
					experimentsString={homeExperimentsString}
				/>
			</div>
		</main>
	);
}
